steps:
 
 # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
         'gcr.io/catalogapi-45046/CatalogService/$MY_PROJECT_ID/myimage:$SHORT_SHA', '.']
  # [END cloudbuild_python_image_yaml]

